---
- name: make a build dir
  file: state=directory name=/root/hdfs-namenode-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/hdfs-namenode-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/hdfs-namenode-dockerized/start.sh mode=0755

- name: build a Docker image for HDFS namenode
  command: docker build -t gitinsky/hdfs-namenode:0.1.2 --rm /root/hdfs-namenode-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/hdfs-namenode:latest --rm /root/hdfs-namenode-dockerized
