---
- name: make a build dir
  file: state=directory name=/root/hdfs-namenode-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/hdfs-namenode-dockerized/Dockerfile

#- name: put elasticsearch_config.sh
#  template: src=elasticsearch_config.sh dest=/root/elasticsearch-dockerized/elasticsearch_config.sh

#- name: put consul-start
#  template: src=consul-start dest=/root/elasticsearch-dockerized/consul-start mode=0755

- name: put run
  template: src=run dest=/root/hdfs-namenode-dockerized/run mode=0755

- name: build a Docker image for HDFS namenode
  command: docker build -t gitinsky/hdfs-namenode:0.1.1 --rm /root/hdfs-namenode-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/hdfs-namenode:latest --rm /root/hdfs-namenode-dockerized
