FROM gitinsky/hdfs:0.1.2
MAINTAINER Git In Sky <support@gitinsky.com>

#RUN mkdir /etc/service/hdfs-namenode
#COPY run /etc/service/hdfs-namenode/run

COPY start.sh /start.sh

CMD ["/start.sh"]

EXPOSE 50070
