#!/bin/sh
set -e
JAVA_HOME=/jdk1.8.0_31/
export JAVA_HOME
chown -R hadoop:hadoop /var/hadoop
if [ ! -e /var/hadoop/dfs ]; then
   sudo -E -u hadoop /hadoop/bin/hdfs namenode -format
fi
exec sudo -E -u hadoop /hadoop/bin/hdfs namenode 1>>/var/log/hdfs-namenode.log 2>&1
